[mysqld]
port=3306
basedir="C:/Users/YK/Desktop/winphp/bin/mysql"
datadir="C:/Users/YK/Desktop/winphp/bin/mysql/data"
bind-address=127.0.0.1
sql_mode=NO_ENGINE_SUBSTITUTION
max_allowed_packet=64M
default-storage-engine=INNODB
